version: '3'
services:
  postgres:
    container_name: tile-postgres
    image: postgres
    restart: always
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5433:5432"
  app:
    container_name: tile-api
    build: ./app/
    restart: always
    ports:
      - "4568:4567"
    depends_on:
      - postgres